### PR TITLE
Add person name validator

### PR DESCRIPTION
**Pull request by lucasdanbatista**
This PR allow to verify if a string is a valid person name (first and last name are required, accents are supported).

### CODE REVIEW

**Review by suragch — COMMENTED** [review]
Thank you for your submission. I was especially glad that you included tests with it. That helped me to understand it more easily.

Names are a hard one because there is so much [naming variety in the world](http://blog.tesol.org/7-naming-customs-from-around-the-world/). For example, many Mongolians in Inner Mongolia don't have a family name so the name Siqingowa wouldn't pass your test. Also, the Chinese name 王小明 doesn't pass even though it includes the family name. On the other side, `hello ,,,,, world` does pass even though it isn't a name.

I recommend that you use your code as an extension method in your app, but I don't think it's ready for the package.

**Comment by lucasdanbatista** [comment]
Thanks for the review, @suragch! I did this in a few minutes and didn't really stop to consider that this is a difficult problem to solve. Analyzing words like "hello world" can be very hard for a package.

**Comment by suragch** [comment]
I'd say that if someone wants to say their name is `hello world`, that wouldn't really be a problem. The bigger problem was the commas in middle of the string: `hello ,,,,, world`.

**Comment by lucasdanbatista** [comment]
Yes, this is a case that my tests not covered. I will refactor they.

**Pull request closed without merging**
